import dataType from "./dataType";
import examples from "./examples";

export const components = {
    components: {
        securitySchemes: {
            bearerAuth: {
                type: "http",
                scheme: "bearer",
                bearerFormat: "JWT",
                in: "header",
                name: "Authorization",
                description: "For accessing the API a valid JWT token must be passed in all the queries in\nthe 'Authorization' heade\
                              A valid JWT token is generated by the API and retourned as answer of a call \
                              to the route /login giving a valid user & password. \
                              The following syntax must be used in the 'Authorization' header : \
                            Bearer: xxxxxx.yyyyyyy.zzzzzz"
            }
        },
        examples: {
            ...examples
        },
        schemas: {
            id: {
                type: "string",
                description: "An id of an area",
                example: "98f01g435796ca42dd2737bt"
            },
            service: {
                type: "string",
                description: "Name of a supported service",
                example: "GITHUB"
            },
            AreaInput: {
                type: "object",
                required: ["trigger", "consequence"],
                properties: {
                    trigger: {
                        type: "object",
                        properties: {
                            inputs: {
                                type: "object",
                                oneOf: [
                                    { $ref: "#/components/schemas/DateTimeConfig" },
                                    { $ref: "#/components/schemas/TimeConfig" },
                                    { $ref: "#/components/schemas/TwitchStreamConfig" },
                                    { $ref: "#/components/schemas/TwitterTweetConfig" },
                                    { $ref: "#/components/schemas/RSSConfig" },
                                    { $ref: "#/components/schemas/DiscordMessageConfig" },
                                    { $ref: "#/components/schemas/GithubIssueConfig" },
                                    { $ref: "#/components/schemas/GithubPulReqConfig" },
                                    { $ref: "#/components/schemas/UnsplashPostConfig" }
                                ]
                            },
                            action: {
                                type: "object",
                                $ref: "#/components/schemas/Action",
                                description: ""
                            }
                        },
                        description: ""
                    },
                    consequence: {
                        type: "object",
                        properties: {
                            inputs: {
                                type: "object",
                                oneOf: [
                                    { $ref: "#/components/schemas/LinkedinPostConfig" },
                                    { $ref: "#/components/schemas/TwitterPostTweetConfig" },
                                    { $ref: "#/components/schemas/TwitterUpdatePictureConfig" },
                                    { $ref: "#/components/schemas/DiscordPostMsgConfig" },
                                    { $ref: "#/components/schemas/GithubCreateIssueConfig" },
                                    { $ref: "#/components/schemas/NotionAddMessageConfig" },
                                    { $ref: "#/components/schemas/DropboxUploadConfig" }
                                ]
                            },
                            reaction: {
                                type: "object",
                                $ref: "#/components/schemas/Reaction",
                                description: ""
                            }
                        },
                        description: ""
                    }
                }
            },
            Area: {
                type: "object",
                required: ["id", "trigger", "consequence"],
                properties: {
                    id: {
                        type: "object",
                        $ref: "#/components/schemas/id",
                        description: "The auto-generated id of the area."
                    },
                    trigger: {
                        type: "object",
                        properties: {
                            inputs: {
                                type: "object",
                                oneOf: [
                                    { $ref: "#/components/schemas/DateTimeConfig" },
                                    { $ref: "#/components/schemas/TimeConfig" },
                                    { $ref: "#/components/schemas/TwitchStreamConfig" },
                                    { $ref: "#/components/schemas/TwitterTweetConfig" },
                                    { $ref: "#/components/schemas/RSSConfig" },
                                    { $ref: "#/components/schemas/DiscordMessageConfig" },
                                    { $ref: "#/components/schemas/GithubIssueConfig" },
                                    { $ref: "#/components/schemas/GithubPulReqConfig" },
                                    { $ref: "#/components/schemas/UnsplashPostConfig" }
                                ]
                            },
                            action: {
                                type: "object",
                                $ref: "#/components/schemas/Action",
                                description: ""
                            }
                        },
                        description: ""
                    },
                    consequence: {
                        type: "object",
                        properties: {
                            inputs: {
                                type: "object",
                                oneOf: [
                                    { $ref: "#/components/schemas/TwitterPostTweetConfig" },
                                    { $ref: "#/components/schemas/LinkedinPostConfig" },
                                    { $ref: "#/components/schemas/TwitterChangePPConfig" },
                                    { $ref: "#/components/schemas/DiscordPostMsgConfig" },
                                    { $ref: "#/components/schemas/GithubCreateIssueConfig" },
                                    { $ref: "#/components/schemas/NotionAddMessageConfig" },
                                    { $ref: "#/components/schemas/DropboxUploadConfig" }
                                ]
                            },
                            reaction: {
                                type: "object",
                                $ref: "#/components/schemas/Reaction",
                                description: ""
                            }
                        },
                        description: ""
                    }
                }
            },
            Areas: {
                type: "array",
                items: {
                    $ref: "#/components/schemas/Area"
                }
            },
            ConfigCron: {
                type: "object",
                properties: {
                    schedule: {
                        type: "string",
                        description: "Cron schedule expression",
                        example: "* * * * *"
                    }
                }
            },
            ...dataType
        }
    }
};